### ISSUE TITLE
Trying to get property of non-object が表示される。

### ISSUE THREAD

**Issue by hirorosoft** [hirorosoft/Retiree#35]
ログイン後、

ErrorException in 080aa0fc57b845b8684aca0c406341aa20d5528f.php line 18:
Trying to get property of non-object (View: /Applications/XAMPP/xamppfiles/htdocs/Retiree/resources/views/career1.blade.php) (View: /Applications/XAMPP/xamppfiles/htdocs/Retiree/resources/views/career1.blade.php)

`in 080aa0fc57b845b8684aca0c406341aa20d5528f.php line 18
at CompilerEngine->handleViewException(object(ErrorException), '1') in compiled.php line 15329
at PhpEngine->evaluatePath('/Applications/XAMPP/xamppfiles/htdocs/Retiree/storage/framework/views/9b73f2cf1724179acb9057de70a6d8f4290f8b8c.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'Career' => null)) in compiled.php line 15364
at CompilerEngine->get('/Applications/XAMPP/xamppfiles/htdocs/Retiree/resources/views/home.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'Career' => null)) in compiled.php line 15196
at View->getContents() in compiled.php line 15184
at View->renderContents() in compiled.php line 15168
at View->render() in compiled.php line 16415
at Response->setContent(object(View)) in compiled.php line 15911
at Response->__construct(object(View)) in compiled.php line 8373
at Router->prepareResponse(object(Request), object(View)) in compiled.php line 9466
at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Authenticate.php line 45
at Authenticate->handle(object(Request), object(Closure))
at call_user_func_array(array(object(Authenticate), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in compiled.php line 9948
at Pipeline->then(object(Closure)) in compiled.php line 9467
at ControllerDispatcher->callWithinStack(object(HomeController), object(Route), object(Request), 'index') in compiled.php line 9454
at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\HomeController', 'index') in compiled.php line 8524
at Route->runController(object(Request)) in compiled.php line 8511
at Route->run(object(Request)) in compiled.php line 8225
at Router->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52`

**Comment by hirorosoft** [comment]
`[2017-11-05 14:59:35] local.ERROR: ErrorException: Trying to get property of non-object in /Applications/XAMPP/xamppfiles/htdocs/Retiree/storage/framework/views/080aa0fc57b845b8684aca0c406341aa20d5528f.php:18
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/Retiree/storage/framework/views/080aa0fc57b845b8684aca0c406341aa20d5528f.php(18): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/Applications/X...', 18, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(15327): include('/Applications/X...')
#2 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(15364): Illuminate\View\Engines\PhpEngine->evaluatePath('/Applications/X...', Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(15196): Illuminate\View\Engines\CompilerEngine->get('/Applications/X...', Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(15184): Illuminate\View\View->getContents()
#5 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(15168): Illuminate\View\View->renderContents()
#6 /Applications/XAMPP/xamppfiles/htdocs/Retiree/storage/framework/views/9b73f2cf1724179acb9057de70a6d8f4290f8b8c.php(45): Illuminate\View\View->render()
#7 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(15327): include('/Applications/X...')
#8 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(15364): Illuminate\View\Engines\PhpEngine->evaluatePath('/Applications/X...', Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(15196): Illuminate\View\Engines\CompilerEngine->get('/Applications/X...', Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(15184): Illuminate\View\View->getContents()
#11 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(15168): Illuminate\View\View->renderContents()
#12 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(16415): Illuminate\View\View->render()
#13 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(15911): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#14 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(8373): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#15 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9466): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#16 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /Applications/XAMPP/xamppfiles/htdocs/Retiree/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /Applications/XAMPP/xamppfiles/htdocs/Retiree/app/Http/Middleware/Authenticate.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /Applications/XAMPP/xamppfiles/htdocs/Retiree/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9467): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9454): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\HomeController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#27 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(8524): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'index')
#28 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(8511): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#29 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(8225): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /Applications/XAMPP/xamppfiles/htdocs/Retiree/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(8226): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(8217): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#36 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(8207): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#37 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#39 /Applications/XAMPP/xamppfiles/htdocs/Retiree/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /Applications/XAMPP/xamppfiles/htdocs/Retiree/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /Applications/XAMPP/xamppfiles/htdocs/Retiree/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /Applications/XAMPP/xamppfiles/htdocs/Retiree/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(13474): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#53 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /Applications/XAMPP/xamppfiles/htdocs/Retiree/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(11964): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#58 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /Applications/XAMPP/xamppfiles/htdocs/Retiree/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#60 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(13213): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#63 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /Applications/XAMPP/xamppfiles/htdocs/Retiree/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#65 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(13150): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#68 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 /Applications/XAMPP/xamppfiles/htdocs/Retiree/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#70 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#71 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#73 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 /Applications/XAMPP/xamppfiles/htdocs/Retiree/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#75 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#76 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#77 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#78 /Applications/XAMPP/xamppfiles/htdocs/Retiree/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#79 /Applications/XAMPP/xamppfiles/htdocs/Retiree/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#80 {main}
`

**Comment by hirorosoft** [comment]
View のキャッシュクリアしてもだめ

**Comment by hirorosoft** [comment]
データベース、マイグレでOK
